
development:
  adapter: postgresql
  database: fakebook_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: fakebook_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: fakebook_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0
